variables:
  AWS_DEPLOY_ROLE: dept-ssgd-role-com-gitlab-deploy

stages:
  - terraform
  # - docker-build

.assume-role-template: &assume_role # Set AWS_ACCOUNT
  - TEMP_OUT=$(aws sts assume-role --role-arn arn:aws:iam::$AWS_ACCOUNT_NUMBER:role/$AWS_DEPLOY_ROLE --role-session-name $CI_JOB_ID)
  - echo $TEMP_OUT
  - export AWS_ACCESS_KEY_ID=$(echo $TEMP_OUT | jq -r '.Credentials''.AccessKeyId')
  - export AWS_SECRET_ACCESS_KEY=$(echo $TEMP_OUT | jq -r '.Credentials''.SecretAccessKey')
  - export AWS_SESSION_TOKEN=$(echo $TEMP_OUT | jq -r '.Credentials''.SessionToken')
  - aws configure set profile.default.aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set profile.default.aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set profile.default.aws_session_token $AWS_SESSION_TOKEN
  - aws configure set default.region $AWS_DEFAULT_REGION
  - aws sts get-caller-identity

terraform-apply:
  stage: terraform
  tags:
    - shared
  script:
    - *assume_role
    - cd terraform
    - chmod +x get-setenv.sh
    - source ./get-setenv.sh configurations/com.tfvars
    - terraform plan -var-file configurations/com.tfvars
    - terraform apply -var-file configurations/com.tfvars -auto-approve
  rules:
  - changes:
    - terraform/*
    - images/*
    - .gitlab-ci.yml

# base-docker-build:
#   stage: docker-build
#   tags:
#     - shared
#   image:
#     name: "gcr.io/kaniko-project/executor:v1.9.0-debug"
#     entrypoint: [""]
#   script:
#     - mkdir -p /kaniko/.docker
#     - version=$(ls ${CI_PROJECT_DIR}/images/gitlab/${SYSTEM_NAME} | egrep -v 'Dockerfile' )
#     - echo $version
#     - echo "{\"credHelpers\":{\"${AWS_ACCOUNT_NUMBER}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com\":\"ecr-login\"}}" > /kaniko/.docker/config.json
#     - >-
#       /kaniko/executor
#       --context "${CI_PROJECT_DIR}/images/gitlab/${SYSTEM_NAME}"
#       --dockerfile "${CI_PROJECT_DIR}/images/gitlab/${SYSTEM_NAME}/Dockerfile"
#       --destination "${AWS_ACCOUNT_NUMBER}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/gitlab/${SYSTEM_NAME}:${version}"
#   parallel:
#     matrix:
#       - SYSTEM_NAME: [ alpine-3-17-3, aws, kaniko-1-9-0 ] # alpine-3-17-3, aws, kaniko-1-9-0
# rules:
# - changes:
#     - images/base/${SYSTEM_NAME}/*

# runner-docker-build:
#   stage: docker-build
#   tags:
#     - shared
#   image:
#     name: "314667246064.dkr.ecr.ap-northeast-2.amazonaws.com/base/kaniko-1-9-0:1.0"
#     entrypoint: [""]
#   script:
#     - mkdir -p /kaniko/.docker
#     - version=$(ls ${CI_PROJECT_DIR}/images/gitlab/${SYSTEM_NAME} | egrep -v 'Dockerfile' | egrep -v 'cubeone' )
#     - echo $version
#     - echo "{\"credHelpers\":{\"${AWS_ACCOUNT_NUMBER}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com\":\"ecr-login\"}}" > /kaniko/.docker/config.json
#     - >-
#       /kaniko/executor
#       --context "${CI_PROJECT_DIR}/images/gitlab/${SYSTEM_NAME}"
#       --dockerfile "${CI_PROJECT_DIR}/images/gitlab/${SYSTEM_NAME}/Dockerfile"
#       --destination "${AWS_ACCOUNT_NUMBER}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/gitlab/${SYSTEM_NAME}:${version}"
#   parallel:
#     matrix:
#       - SYSTEM_NAME: [] # argocli, jdk17, nodejs18, nginx
  # rules:
  # - changes:
  #     - images/gitlab/${SYSTEM_NAME}/*
# k8s-docker-build:
#   stage: docker-build
#   tags:
#     - shared
#   image:
#     name: "314667246064.dkr.ecr.ap-northeast-2.amazonaws.com/base/kaniko-1-9-0:1.0"
#     entrypoint: [""]
#   script:
#     - mkdir -p /kaniko/.docker
#     - version=$(ls ${CI_PROJECT_DIR}/images/k8s/${SYSTEM_NAME} | egrep -v 'Dockerfile' )
#     - echo "{\"credHelpers\":{\"${AWS_ACCOUNT_NUMBER}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com\":\"ecr-login\"}}" > /kaniko/.docker/config.json
#     - >-
#       /kaniko/executor
#       --context "${CI_PROJECT_DIR}/images/k8s/${SYSTEM_NAME}"
#       --dockerfile "${CI_PROJECT_DIR}/images/k8s/${SYSTEM_NAME}/Dockerfile"
#       --destination "${AWS_ACCOUNT_NUMBER}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/k8s/${SYSTEM_NAME}:${version}"
#   parallel:
#     matrix:
#       - SYSTEM_NAME: [ argocli, jdk17 ]
  # rules:
  # - changes:
  #     - images/gitlab/${SYSTEM_NAME}/*
